name: Build ZMK (Charybdis 4x6 RGB / nice!nano v2)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  left:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      shield: charybdis_4x6_rgb_left
      board: nice_nano_v2
      artifact-name: left
  right:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      shield: charybdis_4x6_rgb_right
      board: nice_nano_v2
      artifact-name: right
